### ISSUE TITLE
Rock.Framework.Logging

### ISSUE THREAD

**Issue by ninadkulkarni** [RockFramework/Rock.Logging#1]
In the open source rock framework the logger is not fully functional. It's working for windows apps, console apps but it seems to be not logging anything for web apps. More particularly the log provider that's failing is HttpEndPointLogProvider.

**Comment by bfriesen** [comment]
Fix in progress here: https://github.com/bfriesen/Rock.Logging/tree/no_more_async

**Comment by keithelder** [comment]
Any progress on this, I ran into same issue!

**Comment by mjeaton** [comment]
@bfriesen - is this still an issue, or can this be closed?

**Comment by bfriesen** [comment]
This can be deleted.
